import type {
  DecontextualizedNode,
  ClusterAssignment,
  SynthesisOutline,
  CallTiming,
} from "@/lib/synthesis"
import { formatDuration } from "@/lib/synthesis"

function formatDate(): string {
  return new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
}

export function slugifySynthesis(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 50)
}

function renderTimingTable(timings: CallTiming[], isPolished: boolean): string {
  if (timings.length === 0) return ""

  const totalMs = timings.reduce((sum, t) => sum + (t.durationMs ?? 0), 0)
  const lines: string[] = []

  lines.push(`> [!info]- Generation Statistics`)
  lines.push(`> | Step | Duration |`)
  lines.push(`> |---|---|`)

  for (const t of timings) {
    const dur    = t.durationMs != null ? formatDuration(t.durationMs) : "—"
    const prefix = t.isParallel ? "*(parallel)* " : ""
    lines.push(`> | ${prefix}${t.label} | ${dur} |`)
  }

  lines.push(`> | **Total** | **${formatDuration(totalMs)}** |`)
  if (isPolished) lines.push(`> `)
  if (isPolished) lines.push(`> *Includes final editorial polish (Call D).*`)

  return lines.join("\n")
}

export function renderSynthesisDocument(
  canvasName: string,
  outline: SynthesisOutline,
  decontextualized: DecontextualizedNode[],
  clusters: ClusterAssignment[],
  timings: CallTiming[],
  isPolished = false,
): string {
  const date      = formatDate()
  const totalNodes = clusters.reduce((sum, c) => sum + c.nodeIds.length, 0)
  const stmtMap   = new Map(decontextualized.map(n => [n.id, n.statement]))

  const lines: string[] = []

  // ── YAML front matter ───────────────────────────────────────────────────────
  const totalMs = timings.reduce((sum, t) => sum + (t.durationMs ?? 0), 0)
  lines.push(`---`)
  lines.push(`title: "${isPolished ? "Synthesis (Polished)" : "Synthesis"}: ${canvasName}"`)
  lines.push(`tags: [synthesis, nodepad${isPolished ? ", polished" : ""}]`)
  lines.push(`created: ${new Date().toISOString().slice(0, 10)}`)
  lines.push(`source: nodepad`)
  if (totalMs > 0) lines.push(`generated_in: "${formatDuration(totalMs)}"`)
  lines.push(`---`)
  lines.push(``)

  // ── Title ───────────────────────────────────────────────────────────────────
  lines.push(`# ${canvasName} — Synthesis${isPolished ? " (Polished)" : ""}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // ── Sections ────────────────────────────────────────────────────────────────
  for (const section of outline.sections) {
    lines.push(`## ${section.heading}`)
    lines.push(``)

    if (section.intro) {
      lines.push(section.intro)
      lines.push(``)
    }

    // Synthesis prose — the main output
    if (section.sectionSynthesis) {
      lines.push(section.sectionSynthesis)
      lines.push(``)
    }

    // Source notes — collapsible reference
    const sectionStatements = section.nodeIds
      .map(id => ({ id, stmt: stmtMap.get(id) }))
      .filter((s): s is { id: string; stmt: string } => !!s.stmt)

    if (sectionStatements.length > 0) {
      lines.push(`> [!note]- Source Notes (${sectionStatements.length})`)
      for (const { id, stmt } of sectionStatements) {
        const truncated = stmt.length > 120 ? stmt.slice(0, 120) + "…" : stmt
        lines.push(`> - ${truncated} *(node \`${id.slice(0, 8)}\`)*`)
      }
      lines.push(``)
    }

    // Expounding prompts
    if (section.expandingPrompts.length > 0) {
      lines.push(`> [!example]- Expounding Prompts`)
      section.expandingPrompts.forEach((p, i) => lines.push(`> ${i + 1}. ${p}`))
      lines.push(``)
    }

    // Gaps
    if (section.gaps.length > 0) {
      lines.push(`> [!question]- Gaps in your notes`)
      section.gaps.forEach(g => lines.push(`> - ${g}`))
      lines.push(``)
    }

    lines.push(`---`)
    lines.push(``)
  }

  // ── Timing footer ───────────────────────────────────────────────────────────
  if (timings.length > 0) {
    lines.push(renderTimingTable(timings, isPolished))
    lines.push(``)
  }

  // ── Footer ──────────────────────────────────────────────────────────────────
  lines.push(`*Generated by [nodepad](https://nodepad.space) from ${totalNodes} node${totalNodes !== 1 ? "s" : ""} · ${date}*`)
  lines.push(``)

  return lines.join("\n")
}

export function renderPolishedDocument(
  polishedText: string,
  timings: CallTiming[],
): string {
  const totalMs    = timings.reduce((sum, t) => sum + (t.durationMs ?? 0), 0)
  const timingBlock = renderTimingTable(timings, true)
  const footer     = `\n${timingBlock}\n\n*Generated by [nodepad](https://nodepad.space) · ${formatDate()}*\n`

  // Inject generated_in into the frontmatter (replace existing value if present,
  // or insert before the closing --- of the first frontmatter block)
  let text = polishedText
  if (totalMs > 0) {
    const frontmatterEnd = text.indexOf("\n---", 4)  // skip opening ---
    if (frontmatterEnd !== -1) {
      const hasDuration = /^generated_in:/m.test(text.slice(0, frontmatterEnd))
      if (hasDuration) {
        text = text.replace(/^generated_in:.*$/m, `generated_in: "${formatDuration(totalMs)}"`)
      } else {
        text = text.slice(0, frontmatterEnd) +
          `\ngenerated_in: "${formatDuration(totalMs)}"` +
          text.slice(frontmatterEnd)
      }
    }
  }

  // Append timing + footer, replacing the raw footer if Call D preserved it
  const lastFooterMatch = text.match(/\n\*Generated by \[nodepad\][\s\S]*$/)
  if (lastFooterMatch) {
    return text.slice(0, text.lastIndexOf(lastFooterMatch[0])) + footer
  }
  return text.trimEnd() + "\n\n" + footer
}
