import type { DecontextualizedNode, ClusterAssignment, SynthesisOutline } from "@/lib/synthesis"

function formatDate(): string {
  return new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
}

export function slugifySynthesis(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 50)
}

export function renderSynthesisDocument(
  canvasName: string,
  outline: SynthesisOutline,
  decontextualized: DecontextualizedNode[],
  clusters: ClusterAssignment[],
): string {
  const date      = formatDate()
  const totalNodes = clusters.reduce((sum, c) => sum + c.nodeIds.length, 0)
  const stmtMap   = new Map(decontextualized.map(n => [n.id, n.statement]))

  const lines: string[] = []

  // ── YAML front matter ───────────────────────────────────────────────────────
  lines.push(`---`)
  lines.push(`title: "Synthesis: ${canvasName}"`)
  lines.push(`tags: [synthesis, nodepad]`)
  lines.push(`created: ${new Date().toISOString().slice(0, 10)}`)
  lines.push(`source: nodepad`)
  lines.push(`---`)
  lines.push(``)

  // ── Title + summary ─────────────────────────────────────────────────────────
  lines.push(`# ${canvasName} — Synthesis`)
  lines.push(``)
  lines.push(`> ${outline.summary}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // ── Sections ────────────────────────────────────────────────────────────────
  for (const section of outline.sections) {
    lines.push(`## ${section.heading}`)
    lines.push(``)
    lines.push(section.intro)
    lines.push(``)

    // Self-contained statements with source attribution
    for (const nodeId of section.nodeIds) {
      const stmt = stmtMap.get(nodeId)
      if (!stmt) continue
      lines.push(stmt)
      lines.push(`> *Source: node \`${nodeId.slice(0, 8)}\`*`)
      lines.push(``)
    }

    // Expounding prompts as a collapsible callout
    if (section.expandingPrompts.length > 0) {
      lines.push(`> [!example]- Expounding Prompts`)
      section.expandingPrompts.forEach((p, i) => lines.push(`> ${i + 1}. ${p}`))
      lines.push(``)
    }

    // Gaps
    if (section.gaps.length > 0) {
      lines.push(`> [!question]- Gaps in your notes`)
      section.gaps.forEach(g => lines.push(`> - ${g}`))
      lines.push(``)
    }

    lines.push(`---`)
    lines.push(``)
  }

  // ── Footer ──────────────────────────────────────────────────────────────────
  lines.push(`*Generated by [nodepad](https://nodepad.space) from ${totalNodes} node${totalNodes !== 1 ? "s" : ""} · ${date}*`)
  lines.push(``)

  return lines.join("\n")
}
